#main program

import exceptions

def main():
    exceptions.multiply_two_numbers_validate()

main()